language:
  - node_js
node_js:
  - "6"
cache:
  - yarn
branches:
  only:
    - dev
install:
  - yarn
script:
  - yarn generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  on:
    branch: dev
  local_dir: dist
